import * as React from 'react'
import Typography from '@mui/material/Typography'
import Container from '@mui/material/Container'
import TopSlogan from '../components/TopSlogan'
import NFTCollectionsList from '../components/NFTCollectionsList'
import AssetsList from '../components/AssetsList'

function ExplorePage() {
  return (
    <>
      <TopSlogan
        header="Explore NFTs from top creators!"
        summary="Have a rough dream that you want to make it come true as a unique art auto generated by AI? How about linking the art to your wallet automatically? Crazy Bee will serve that for you!"
        mainCTAText="Ready to create NFT?"
        mainCTALink="/ai/creator"
        enableSignUpPopup={true}
      />
      <Container>
        <Typography component="h4" variant="h4" align="left" color="text.primary" gutterBottom>
          Recent NFT Collections
        </Typography>
      </Container>
      <NFTCollectionsList nftCollectionsLimit={4} />
      <Container sx={{ mt: 5 }}>
        <Typography component="h4" variant="h4" align="left" color="text.primary" gutterBottom>
          Recent Assets
        </Typography>
      </Container>
      <AssetsList />
    </>
  )
}

export default ExplorePage
